# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rwMetropolosC <- function(sigma, x0, N) {
    .Call('_SC19043_rwMetropolosC', PACKAGE = 'SC19043', sigma, x0, N)
}

